### ISSUE TITLE
capture both landscape and portrait

### ISSUE THREAD

**Issue by pmagnuson** [mmcc007/screenshots#162]
I would like to capture both landscape and portrait screenshots on a device.  My `screenshots.yaml` file is throwing an error.  

```
Error on line 21, column 5: Duplicate mapping key.
   ╷
21 │     iPhone Xs Max:
   │     ^^^^^^^^^^^^^
```

It seems like either the `screenshots.yaml` file should allow one device to run in both landscape and portrait or there needs to be a way in the `main_test.dart` file to specify a device rotation.  I have not found either mechanism.   

`screenshots.yaml`
```yaml
# Screen capture tests
# Note: flutter driver expects a pair of files eg, main.dart and main_test.dart
tests:
  - test_driver/main.dart

# Interim location of screenshots from tests before processing
staging: /tmp/screenshots

# A list of locales supported in app
locales:
  - en-US
  # - fr-CA

# A list of devices to run tests on
devices:
  ios:
    iPhone Xs Max:
      orientation: Portrait
    iPad Pro (12.9-inch) (2nd generation):
      orientation: Portrait
    iPhone Xs Max:
      orientation: Landscape
    iPad Pro (12.9-inch) (2nd generation):
      orientation: Landscape
  android:
    Nexus_7_2012_API_25:
      orientation: Portrait
    Nexus_7_2012_API_25:
      orientation: Landscape

# Frame screenshots
frame: false

# Run mode can be one of 'normal' (default), 'recording', 'comparison' or 'archive'.

# If run mode is 'recording' or 'comparison', a directory is required for recorded images.
recording: /tmp/screenshots_record

# If not intending to upload screenshots, images can be stored in an archive dir.
# This over-rides output to fastlane dirs.
# If run mode is 'archive', a directory is required for archived images.
archive: /tmp/screenshots_archive
```

**Comment by mmcc007** [comment]
Enabling multiple locales per device would be an enhancement.

When support is added the multi locales per device could be specified using something like
```yaml
    Nexus_7_2012_API_25:
      orientation: 
        - Portrait
        - Landscape
```
