### ISSUE TITLE
Landscape not working

### ISSUE THREAD

**Issue by pmagnuson** [mmcc007/screenshots#163]
Images are coming out in portrait even though LandscapeRight is specified in yaml.  Same results with LandscapeLeft

```yaml
# A list of devices to run tests on
devices:
  ios:
    iPhone Xs Max:
      orientation: LandscapeRight
    iPad Pro (12.9-inch) (2nd generation):
      orientation: LandscapeRight
  android:
    Nexus_7_2012_API_25:
      orientation: LandscapeRight

# Frame screenshots
frame: false
```
