### ISSUE TITLE
Unhandled exception: command failed: exitcode=1

### ISSUE THREAD

**Issue by agordeev** [mmcc007/screenshots#197]
I'm getting `Unhandled exception:
command failed: exitcode=1, cmd='plutil -convert json -o - /Users/andrey/Library/Developer/CoreSimulator/Devices/91F6AB11-F957-4412-906D-3E602524A122/data/Library/Preferences/.GlobalPreferences.plist', workingDir=.` when running `screenshots`.

`screenshots -v`:

```
[  +68 ms] Starting flutter daemon...
[  +11 ms] executing: flutter daemon
[ +832 ms] <== Starting device daemon...
[   +4 ms] <== [{"event":"daemon.connected","params":{"version":"0.5.3","pid":4256}}]
[   +3 ms] ==> [{"method":"device.enable","id":0}]
[        ] waiting for response: {method: device.enable, id: 0}
[  +19 ms] <== [{"id":0}]
[+5024 ms] executing: [./] sh -c ios-deploy -c || echo "no attached devices"
[   +1 ms] <== [{"event":"device.added","params":{"id":"emulator-5554","name":"Android SDK built for
x86","platform":"android-x86","emulator":true,"category":"mobile","platformType":"android","ephemeral":true,"emulatorId":"Pixel_2_XL_Oreo"}}]
[   +4 ms] <== [{"event":"device.added","params":{"id":"emulator-5556","name":"Android SDK built for
x86","platform":"android-x86","emulator":true,"category":"mobile","platformType":"android","ephemeral":true,"emulatorId":"10.1_WXGA_Tablet_API_27"}}]
[   +1 ms] <== [{"event":"device.added","params":{"id":"1A5C302F-1156-4A9E-A269-1B0B80B2BCBC","name":"iPhone 11
Pro","platform":"ios","emulator":true,"category":"mobile","platformType":"ios","ephemeral":true,"emulatorId":"apple_ios_simulator"}}]
[   +1 ms] <== [{"event":"device.added","params":{"id":"F0DB2C52-2165-4184-B8A8-ACF94CCBF23F","name":"iPad (7th
generation)","platform":"ios","emulator":true,"category":"mobile","platformType":"ios","ephemeral":true,"emulatorId":"apple_ios_simulator"}}]
[ +116 ms] Starting flutter daemon... (completed in 6.0s)
[   +1 ms] ==> [{"method":"device.getDevices","id":1}]
[        ] waiting for response: {method: device.getDevices, id: 1}
[  +12 ms] <== [{"id":1,"result":[{"id":"emulator-5554","name":"Android SDK built for
x86","platform":"android-x86","emulator":true,"category":"mobile","platformType":"android","ephemeral":true,"emulatorId":"Pixel_2_XL_Oreo"},{"id":"emulator-5556","name":"Android SDK built for
x86","platform":"android-x86","emulator":true,"category":"mobile","platformType":"android","ephemeral":true,"emulatorId":"10.1_WXGA_Tablet_API_27"},{"id":"1A5C302F-1156-4A9E-A269-1B0B80B2BCBC","n
ame":"iPhone 11
Pro","platform":"ios","emulator":true,"category":"mobile","platformType":"ios","ephemeral":true,"emulatorId":"apple_ios_simulator"},{"id":"F0DB2C52-2165-4184-B8A8-ACF94CCBF23F","name":"iPad (7th
generation)","platform":"ios","emulator":true,"category":"mobile","platformType":"ios","ephemeral":true,"emulatorId":"apple_ios_simulator"}]}]
[  +16 ms] daemonDevice=id: emulator-5554, name: Android SDK built for x86, category: mobile, platformType: android platform: android-x86, emulator: true, ephemeral: true, emulatorId:
Pixel_2_XL_Oreo, iosModel: null
[   +1 ms] daemonDevice=id: emulator-5556, name: Android SDK built for x86, category: mobile, platformType: android platform: android-x86, emulator: true, ephemeral: true, emulatorId:
10.1_WXGA_Tablet_API_27, iosModel: null
[        ] daemonDevice=id: 1A5C302F-1156-4A9E-A269-1B0B80B2BCBC, name: iPhone 11 Pro, category: mobile, platformType: ios platform: ios, emulator: true, ephemeral: true, emulatorId:
apple_ios_simulator, iosModel: null
[        ] daemonDevice=id: F0DB2C52-2165-4184-B8A8-ACF94CCBF23F, name: iPad (7th generation), category: mobile, platformType: ios platform: ios, emulator: true, ephemeral: true, emulatorId:
apple_ios_simulator, iosModel: null
[   +2 ms] ==> [{"method":"emulator.getEmulators","id":2}]
[        ] waiting for response: {method: emulator.getEmulators, id: 2}
[  +32 ms] <== [{"id":2,"result":[{"id":"10.1_WXGA_Tablet_API_27","name":"10.1  WXGA (Tablet) API 27","category":"mobile","platformType":"android"},{"id":"Galaxy_S8_Oreo_8.1","name":"Galaxy S8
Oreo 8.1","category":"mobile","platformType":"android"},{"id":"Pixel_2_XL_Oreo","name":"Pixel 2 XL Oreo","category":"mobile","platformType":"android"},{"id":"apple_ios_simulator","name":"iOS
Simulator","category":"mobile","platformType":"ios"}]}]
[   +1 ms] daemonEmulator=id: 10.1_WXGA_Tablet_API_27, name: 10.1  WXGA (Tablet) API 27, category: mobile, platformType: android
[        ] daemonEmulator=id: Galaxy_S8_Oreo_8.1, name: Galaxy S8 Oreo 8.1, category: mobile, platformType: android
[        ] daemonEmulator=id: Pixel_2_XL_Oreo, name: Pixel 2 XL Oreo, category: mobile, platformType: android
[        ] daemonEmulator=id: apple_ios_simulator, name: iOS Simulator, category: mobile, platformType: ios
[ +137 ms] executing: [./] xcrun simctl list devices --json
[  +33 ms] executing: [./] chmod u+x /tmp/screenshots/resources/script/android-wait-for-emulator
[  +11 ms] executing: [./] chmod u+x /tmp/screenshots/resources/script/android-wait-for-emulator-to-stop
[  +10 ms] executing: [./] chmod u+x /tmp/screenshots/resources/script/simulator-controller
[  +11 ms] executing: [./] chmod u+x /tmp/screenshots/resources/script/sim_orientation.scpt
[   +5 ms] Clearing images in ios/fastlane/screenshots/en for 'iPhone Xs Max'...
[   +2 ms] Clearing images in ios/fastlane/screenshots/ru for 'iPhone Xs Max'...
[ +118 ms] executing: [./] xcrun simctl list devices --json
[  +24 ms] executing: [./] plutil -convert json -o - /Users/andrey/Library/Developer/CoreSimulator/Devices/91F6AB11-F957-4412-906D-3E602524A122/data/Library/Preferences/.GlobalPreferences.plist
Unhandled exception:
command failed: exitcode=1, cmd='plutil -convert json -o - /Users/andrey/Library/Developer/CoreSimulator/Devices/91F6AB11-F957-4412-906D-3E602524A122/data/Library/Preferences/.GlobalPreferences.plist', workingDir=.
#0      cmd (package:screenshots/src/utils.dart:361:5)
#1      getIosSimulatorLocale (package:screenshots/src/utils.dart:178:19)
#2      Screenshots.runTestsOnAll (package:screenshots/src/run.dart:226:40)
<asynchronous suspension>
#3      Screenshots.run (package:screenshots/src/run.dart:127:11)
<asynchronous suspension>
#4      screenshots.<anonymous closure> (package:screenshots/src/run.dart:42:26)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:tool_base/src/base/context.dart:154:29)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1463:12)
#10     AppContext.run (package:tool_base/src/base/context.dart:153:18)
<asynchronous suspension>
#11     runInContext (package:screenshots/src/context_runner.dart:16:24)
<asynchronous suspension>
#12     screenshots (package:screenshots/src/run.dart:41:12)
<asynchronous suspension>
#13     main (file:///Users/andrey/.pub-cache/hosted/pub.dartlang.org/screenshots-2.1.1/bin/main.dart:122:25)
<asynchronous suspension>
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

`screenshots.yaml`:

```yaml
# Screen capture tests
# Note: flutter driver expects a pair of files eg, main.dart and main_test.dart
tests:
  - test_driver/main.dart

# Interim location of screenshots from tests before processing
staging: /tmp/screenshots

# A list of locales supported in app
locales:
  - en
  - ru

# A list of devices to run tests on
devices:
  ios:
    iPhone Xs Max:
      frame: true
  # android:
  #   Pixel_2_XL_Oreo:

# Frame screenshots
frame: true

# Run mode can be one of 'normal' (default), 'recording', 'comparison' or 'archive'.

# If run mode is 'recording' or 'comparison', a directory is required for recorded images.
recording: /tmp/screenshots_record

# If not intending to upload screenshots, images can be stored in an archive dir.
# This over-rides output to fastlane dirs.
# If run mode is 'archive', a directory is required for archived images.
archive: /tmp/screenshots_archive
```

It works for iPhone 11 Pro though:

```yaml
devices:
  ios:
    iPhone 11 Pro:
      frame: false
```
