### ISSUE TITLE
Cannot use with integration_test dependency?

### ISSUE THREAD

**Issue by JoseFMP** [mmcc007/screenshots#223]
A fresh flutter projects promps this error when adding the dependency of `screenshots`

```
because every version of integration_test from sdk depends on file 6.0.0-nullsafety.4 and screenshots >=1.0.0 depends on file ^5.0.7, integration_test from sdk is incompatible with screenshots >=1.0.0.

So, because tenants depends on both screenshots 2.1.1 and integration_test any from sdk, version solving failed.
pub get failed (1; So, because tenants depends on both screenshots 2.1.1 and integration_test any from sdk, version solving failed.)
exit code 1
```

where
```
environment:
  sdk: ">=2.7.0 <3.0.0"
```

and 
```
dev_dependencies:
  screenshots: 2.1.1
  test: 1.16.0-nullsafety.9
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
```

Which version is supposed to be compatible with current flutter stable release?

**Comment by amorenew** [comment]
@JoseFMP I have all of these but not sure which one to exclude
```
dependency_overrides:
  flutter_svg: ^0.19.0
  freezed_annotation: ^0.12.0
  analyzer: ^0.39.17
  process: ^4.0.0-nullsafety.2
  platform: ^3.0.0-nullsafety.2
  file: ^6.0.0-nullsafety.2
```
