### ISSUE TITLE
Stuck after starting Android emulator in locale en-US

### ISSUE THREAD

**Issue by mmcc007** [mmcc007/screenshots#29]
I'm seeing this issue as well with Android emulators (iOS simulators work fine), and am using only en-US:

screenshots.yaml:
```
...
locales:
#  - fr-CA
  - en-US # this is assumed to be the default for your test machine.
...
devices:
  ios:
    - iPhone X
    - iPad Pro (12.9-inch) (2nd generation)
  android:
    - Nexus 6P
...
```

Issue exists for both Nexus 5X and 6P.
```
$ emulator -list-avds
Nexus_5X_API_27
Nexus_6P_API_28
```

_Originally posted by @noumaans in https://github.com/mmcc007/screenshots/issues/19#issuecomment-477313724_
