### ISSUE TITLE
Specify frame at platform/device level

### ISSUE THREAD

**Issue by kentcb** [mmcc007/screenshots#50]
When generating screenshots, I have found I want frames enabled for Android and disabled for iOS. This is a little annoying because now I have to switch my config around every time I run (or have a separate config for each platform).

It would be nice if the `frame` configuration parameter was hoisted so that I could specify it per platform, or even override it per device:

```yaml
tests:
  - test_driver/app.dart

staging: /tmp/screenshots

locales:
  - en-AU

devices:
  ios:
    - iPhone 7 Plus
      frame: false
    - iPad Pro (12.9-inch) (2nd generation)
      frame: false
  android:
    - Nexus 9
      frame: true
    - Nexus 6P
      frame: true
```
